---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by wuxin.
--- DateTime: 2019-11-14 18:13
---
local typedefs = require "kong.db.schema.typedefs"

return {
    name = "ejuoauthresource",
    fields = {

                { run_on = typedefs.run_on },
                { protocols = typedefs.protocols_http },

                { config = {
                            type = "record",

                            fields = {
                                        { tokenHeaderName = { type = "string", required = true, default="authorization"} },
                                        { tokenValidURL = { type = "string", required = true, default = "/introspect" } },
                                        { resourceId = { type = "string", required = true, default = "resourceId" } },
                                        { resourceSecret = { type = "string", required = true, default = "resourceSecret123" } },

                                     },

                            },

                },

               },

}